# See https://pre-commit.com for more information

repos:
  # Export project dependencies to a file, to be read by pip-audit
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.5
    hooks:
      - id: uv-export
        name: Export dependencies (for security audit)
        args:
          [--frozen, --no-emit-project, --no-dev, -o, appcity/dependencies.txt]

  # Check dependencies for known CVEs.
  - repo: https://github.com/pypa/pip-audit
    rev: v2.8.0
    hooks:
      - id: pip-audit
        name: Dependency vulnerability audit
        args: [-r, appcity/dependencies.txt, --disable-pip]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      # Run the linter, automatically fixing issues when possible.
      - id: ruff
        name: Ruff linting
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        name: Ruff formatting
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: Mypy static type checker
        additional_dependencies:
          - pydantic
          - types-requests
          - pandera[mypy]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.5.5"
    hooks:
      - id: remove-crlf

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        name: Strip output from Jupyter notebooks
